export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";

export const HRM_SAU_REQUEST = "HRM_SAU_REQUEST";
export const HRM_SAU_SUCCESS = "HRM_SAU_SUCCESS";
export const HRM_SAU_FAILURE = "HRM_SAU_FAILURE";

export const PROCESS_DEFINITION_REQUEST = "PROCESS_DEFINITION_REQUEST";
export const PROCESS_DEFINITION_SUCCESS = "PROCESS_DEFINITION_SUCCESS";
export const PROCESS_DEFINITION_FAILURE = "PROCESS_DEFINITION_FAILURE";

export const PROCESS_DEFINITION_XML_REQUEST = "PROCESS_DEFINITION_XML_REQUEST";
export const PROCESS_DEFINITION_XML_SUCCESS = "PROCESS_DEFINITION_XML_SUCCESS";
export const PROCESS_DEFINITION_XML_FAILURE = "PROCESS_DEFINITION_XML_FAILURE";

export const GET_PERSONAL_REQUEST = "GET_PERSONAL_REQUEST";
export const GET_PERSONAL_SUCCESS = "GET_PERSONAL_SUCCESS";
export const GET_PERSONAL_FAILURE = "GET_PERSONAL_FAILURE";

export const GET_PERSONALINFO_REQUEST = "GET_PERSONALINFO_REQUEST";
export const GET_PERSONALINFO_SUCCESS = "GET_PERSONALINFO_SUCCESS";
export const GET_PERSONALINFO_FAILURE = "GET_PERSONALINFO_FAILURE";

export const UPDATE_PERSONAL_REQUEST = "UPDATE_PERSONAL_REQUEST";
export const UPDATE_PERSONAL_SUCCESS = "UPDATE_PERSONAL_SUCCESS";
export const UPDATE_PERSONAL_FAILURE = "UPDATE_PERSONAL_FAILURE";

export const NEW_PROCESS_INSTANCE_REQUEST = "NEW_PROCESS_INSTANCE_REQUEST";
export const NEW_PROCESS_INSTANCE_SUCCESS = "NEW_PROCESS_INSTANCE_SUCCESS";
export const NEW_PROCESS_INSTANCE_FAILURE = "NEW_PROCESS_INSTANCE_FAILURE";

export const NEW_PROCESS_INSTANCE_VARIABLES_REQUEST =
  "NEW_PROCESS_INSTANCE_VARIABLES_REQUEST";
export const NEW_PROCESS_INSTANCE_VARIABLES_SUCCESS =
  "NEW_PROCESS_INSTANCE_VARIABLES_SUCCESS";
export const NEW_PROCESS_INSTANCE_VARIABLES_FAILURE =
  "NEW_PROCESS_INSTANCE_VARIABLES_FAILURE";

export const FORM_KEY_REQUEST = "FORM_KEY_REQUEST";
export const FORM_KEY_SUCCESS = "FORM_KEY_SUCCESS";
export const FORM_KEY_FAILURE = "FORM_KEY_FAILURE";

export const TASKS_REQUEST = "TASKS_REQUEST";
export const TASKS_SUCCESS = "TASKS_SUCCESS";
export const TASKS_FAILURE = "TASKS_FAILURE";

export const TASK_FORM_KEY_REQUEST = "TASK_FORM_KEY_REQUEST";
export const TASK_FORM_KEY_SUCCESS = "TASK_FORM_KEY_SUCCESS";
export const TASK_FORM_KEY_FAILURE = "TASK_FORM_KEY_FAILURE";

export const TASK_SUBMITTED_REQUEST = "TASK_SUBMITTED_REQUEST";
export const TASK_SUBMITTED_SUCCESS = "TASK_SUBMITTED_SUCCESS";
export const TASK_SUBMITTED_FAILURE = "TASK_SUBMITTED_FAILURE";

export const TASK_VARIABLES_REQUEST = "TASK_VARIABLES_REQUEST";
export const TASK_VARIABLES_SUCCESS = "TASK_VARIABLES_SUCCESS";
export const TASK_VARIABLES_FAILURE = "TASK_VARIABLES_FAILURE";

export const PROCESS_DEPLOYMENT_REQUEST = "PROCESS_DEPLOYMENT_REQUEST";
export const PROCESS_DEPLOYMENT_SUCCESS = "PROCESS_DEPLOYMENT_SUCCESS";
export const PROCESS_DEPLOYMENT_FAILURE = "PROCESS_DEPLOYMENT_FAILURE";
//              BACKEND API'S
export const INITIATE_GET_DATA_REQUEST = "INITIATE_GET_DATA_REQUEST";
export const INITIATE_GET_DATA_SUCCESS = "INITIATE_GET_DATA_SUCCESS";
export const INITIATE_GET_DATA_FAILURE = "INITIATE_GET_DATA_FAILURE";

export const GET_DEPT_REQUEST = "GET_DEPT_REQUEST";
export const GET_DEPT_SUCCESS = "GET_DEPT_SUCCESS";
export const GET_DEPT_FAILURE = "GET_DEPT_FAILURE";

export const INITIATE_FORM_CREATE_REQUEST = "INITIATE_FORM_CREATE_REQUEST";
export const INITIATE_FORM_CREATE_SUCCESS = "INITIATE_FORM_CREATE_SUCCESS";
export const INITIATE_FORM_CREATE_FAILURE = "INITIATE_FORM_CREATE_FAILURE";

export const CLASSIFICATION_REQUEST = "CLASSIFICATION_REQUEST";
export const CLASSIFICATION_SUCCESS = "CLASSIFICATION_SUCCESS";
export const CLASSIFICATION_FAILURE = "CLASSIFICATION_FAILURE";

export const PA_DASHBOARD_REQUEST = "PA_DASHBOARD_REQUEST";
export const PA_DASHBOARD_SUCCESS = "PA_DASHBOARD_SUCCESS";
export const PA_DASHBOARD_FAILURE = "PA_DASHBOARD_FAILURE";

export const TYPE_REQUEST = "TYPE_REQUEST";
export const TYPE_SUCCESS = "TYPE_SUCCESS";
export const TYPE_FAILURE = "TYPE_FAILURE";

export const ROLES_REQUEST = "ROLES_REQUEST";
export const ROLES_SUCCESS = "ROLES_SUCCESS";
export const ROLES_FAILURE = "ROLES_FAILURE";

export const GROUPS_REQUEST = "GROUPS_REQUEST";
export const GROUPS_SUCCESS = "GROUPS_SUCCESS";
export const GROUPS_FAILURE = "GROUPS_FAILURE";

export const DRAFT_DATA_REQUEST = "DRAFT_DATA_REQUEST";
export const DRAFT_DATA_SUCCESS = "DRAFT_DATA_SUCCESS";
export const DRAFT_DATA_FAILURE = "DRAFT_DATA_FAILURE";

export const OUTBOX_DATA_REQUEST = "OUTBOX_DATA_REQUEST";
export const OUTBOX_DATA_SUCCESS = "OUTBOX_DATA_SUCCESS";
export const OUTBOX_DATA_FAILURE = "OUTBOX_DATA_FAILURE";

export const OUTBOX_DATA_EXPORT_REQUEST = "OUTBOX_DATA_EXPORT_REQUEST";
export const OUTBOX_DATA_EXPORT_SUCCESS = "OUTBOX_DATA_EXPORT_SUCCESS";
export const OUTBOX_DATA_EXPORT_FAILURE = "OUTBOX_DATA_EXPORT_FAILURE";

export const OUTBOX_ROW_REQUEST = "OUTBOX_ROW_REQUEST";
export const OUTBOX_ROW_SUCCESS = "OUTBOX_ROW_SUCCESS";
export const OUTBOX_ROW_FAILURE = "OUTBOX_ROW_FAILURE";

export const INBOX_DATA_REQUEST = "INBOX_DATA_REQUEST";
export const INBOX_DATA_SUCCESS = "INBOX_DATA_SUCCESS";
export const INBOX_DATA_FAILURE = "INBOX_DATA_FAILURE";

export const ENCLOSURE_DATA_REQUEST = "ENCLOSURE_DATA_REQUEST";
export const ENCLOSURE_DATA_SUCCESS = "ENCLOSURE_DATA_SUCCESS";
export const ENCLOSURE_DATA_FAILURE = "ENCLOSURE_DATA_FAILURE";

export const NOTING_DATA_REQUEST = "NOTING_DATA_REQUEST";
export const NOTING_DATA_SUCCESS = "NOTING_DATA_SUCCESS";
export const NOTING_DATA_FAILURE = "NOTING_DATA_FAILURE";

export const NOTING_FILE_REQUEST = "NOTING_FILE_REQUEST";
export const NOTING_FILE_SUCCESS = "NOTING_FILE_SUCCESS";
export const NOTING_FILE_FAILURE = "NOTING_FILE_FAILURE";

export const ENCLOSURE_FILE_REQUEST = "ENCLOSURE_FILE_REQUEST";
export const ENCLOSURE_FILE_SUCCESS = "ENCLOSURE_FILE_SUCCESS";
export const ENCLOSURE_FILE_FAILURE = "ENCLOSURE_FILE_FAILURE";

export const SEND_FILE_REQUEST = "SEND_FILE_REQUEST";
export const SEND_FILE_SUCCESS = "SEND_FILE_SUCCESS";
export const SEND_FILE_FAILURE = "SEND_FILE_FAILURE";

export const FILE_REQUEST = "FILE_REQUEST";
export const FILE_SUCCESS = "FILE_SUCCESS";
export const FILE_FAILURE = "FILE_FAILURE";

export const SFDT_REQUEST = "SFDT_REQUEST";
export const SFDT_SUCCESS = "SFDT_SUCCESS";
export const SFDT_FAILURE = "SFDT_FAILURE";

export const FLAG_REQUEST = "FLAG_REQUEST";
export const FLAG_SUCCESS = "FLAG_SUCCESS";
export const FLAG_FAILURE = "FLAG_FAILURE";

export const PIN_REQUEST = "PIN_REQUEST";
export const PIN_SUCCESS = "PIN_SUCCESS";
export const PIN_FAILURE = "PIN_FAILURE";

export const TEST_URL_REQUEST = "TEST_URL_REQUEST";
export const TEST_URL_SUCCESS = "TEST_URL_SUCCESS";
export const TEST_URL_FAILURE = "TEST_URL_FAILURE";

export const CREATE_PF_REQUEST = "CREATE_PF_REQUEST";
export const CREATE_PF_SUCCESS = "CREATE_PF_SUCCESS";
export const CREATE_PF_FAILURE = "CREATE_PF_FAILURE";

export const PA_REQUEST = "PA_REQUEST";
export const PA_SUCCESS = "PA_SUCCESS";
export const PA_FAILURE = "PA_FAILURE";

export const UPDATE_SUBJECT_DRAFT_REQUEST = "UPDATE_SUBJECT_DRAFT_REQUEST";
export const UPDATE_SUBJECT_DRAFT_SUCCESS = "UPDATE_SUBJECT_DRAFT_SUCCESS";
export const UPDATE_SUBJECT_DRAFT_FAILURE = "UPDATE_SUBJECT_DRAFT_FAILURE";

export const PATYPE_REQUEST = "PATYPE_REQUEST";
export const PATYPE_SUCCESS = "PATYPE_SUCCESS";
export const PATYPE_FAILURE = "PATYPE_FAILURE";

export const PF_REQUEST = "PF_REQUEST";
export const PF_SUCCESS = "PF_SUCCESS";
export const PF_FAILURE = "PF_FAILURE";

export const PFILE_REQUEST = "PFILE_REQUEST";
export const PFILE_SUCCESS = "PFILE_SUCCESS";
export const PFILE_FAILURE = "PFILE_FAILURE";

export const PA_TABLE_REQUEST = "PA_TABLE_REQUEST";
export const PA_TABLE_SUCCESS = "PA_TABLE_SUCCESS";
export const PA_TABLE_FAILURE = "PA_TABLE_FAILURE";

export const ANNOT_REQUEST = "ANNOT_REQUEST";
export const ANNOT_SUCCESS = "ANNOT_SUCCESS";
export const ANNOT_FAILURE = "ANNOT_FAILURE";

export const EXTERNAL_ANNOT_REQUEST = "EXTERNAL_ANNOT_REQUEST";
export const EXTERNAL_ANNOT_SUCCESS = "EXTERNAL_ANNOT_SUCCESS";
export const EXTERNAL_ANNOT_FAILURE = "EXTERNAL_ANNOT_FAILURE";

export const GET_ANNOT_REQUEST = "GET_ANNOT_REQUEST";
export const GET_ANNOT_SUCCESS = "GET_ANNOT_SUCCESS";
export const GET_ANNOT_FAILURE = "GET_ANNOT_FAILURE";

export const SEND_FILES_REQUEST = "SEND_FILES_REQUEST";
export const SEND_FILES_SUCCESS = "SEND_FILES_SUCCESS";
export const SEND_FILES_FAILURE = "SEND_FILES_FAILURE";

export const QICK_SIGN_REQUEST = "QICK_SIGN_REQUEST";
export const QICK_SIGN_SUCCESS = "QICK_SIGN_SUCCESS";
export const QICK_SIGN_FAILURE = "QICK_SIGN_FAILURE";

export const SAVE_FILES_REQUEST = "SAVE_FILES_REQUEST";
export const SAVE_FILES_SUCCESS = "SAVE_FILES_SUCCESS";
export const SAVE_FILES_FAILURE = "SAVE_FILES_FAILURE";

export const ANNEXURE_FILE_REQUEST = "ANNEXURE_FILE_REQUEST";
export const ANNEXURE_FILE_SUCCESS = "ANNEXURE_FILE_SUCCESS";
export const ANNEXURE_FILE_FAILURE = "ANNEXURE_FILE_FAILURE";

export const PC_ANNEXURE_FILE_REQUEST = "PC_ANNEXURE_FILE_REQUEST";
export const PC_ANNEXURE_FILE_SUCCESS = "PC_ANNEXURE_FILE_SUCCESS";
export const PC_ANNEXURE_FILE_FAILURE = "PC_ANNEXURE_FILE_FAILURE";

export const ANNEXURE_LIST_REQUEST = "ANNEXURE_LIST_REQUEST";
export const ANNEXURE_LIST_SUCCESS = "ANNEXURE_LIST_SUCCESS";
export const ANNEXURE_LIST_FAILURE = "ANNEXURE_LIST_FAILURE";

export const GROUP_LIST_REQUEST = "GROUP_LIST_REQUEST";
export const GROUP_LIST_SUCCESS = "GROUP_LIST_SUCCESS";
export const GROUP_LIST_FAILURE = "GROUP_LIST_FAILURE";

export const HRM_LIST_REQUEST = "HRM_LIST_REQUEST";
export const HRM_LIST_SUCCESS = "HRM_LIST_SUCCESS";
export const HRM_LIST_FAILURE = "HRM_LIST_FAILURE";

export const SERVICE_LIST_REQUEST = "SERVICE_LIST_REQUEST";
export const SERVICE_LIST_SUCCESS = "SERVICE_LIST_SUCCESS";
export const SERVICE_LIST_FAILURE = "SERVICE_LIST_FAILURE";

export const USER_ROLES_REQUEST = "USER_ROLES_REQUEST";
export const USER_ROLES_SUCCESS = "USER_ROLES_SUCCESS";
export const USER_ROLES_FAILURE = "USER_ROLES_FAILURE";

export const MIS_LIST_REQUEST = "MIS_LIST_REQUEST";
export const MIS_LIST_SUCCESS = "MIS_LIST_SUCCESS";
export const MIS_LIST_FAILURE = "MIS_LIST_FAILURE";

export const MIS_DETAIL_LIST_REQUEST = "MIS_DETAIL_LIST_REQUEST";
export const MIS_DETAIL_LIST_SUCCESS = "MIS_DETAIL_LIST_SUCCESS";
export const MIS_DETAIL_LIST_FAILURE = "MIS_DETAIL_LIST_FAILURE";

export const DELETE_ANNEXURE_REQUEST = "DELETE_ANNEXURE_REQUEST";
export const DELETE_ANNEXURE_SUCCESS = "DELETE_ANNEXURE_SUCCESS";
export const DELETE_ANNEXURE_FAILURE = "DELETE_ANNEXURE_FAILURE";

export const UPDATE_ANNEXURE_REQUEST = 'UPDATE_ANNEXURE_REQUEST'
export const UPDATE_ANNEXURE_SUCCESS = 'UPDATE_ANNEXURE_SUCCESS'
export const UPDATE_ANNEXURE_FAILURE = 'UPDATE_ANNEXURE_FAILURE'

export const CREATE_PANOTING_REQUEST = "CREATE_PANOTING_REQUEST";
export const CREATE_PANOTING_SUCCESS = "CREATE_PANOTING_SUCCESS";
export const CREATE_PANOTING_FAILURE = "CREATE_PANOTING_FAILURE";

export const ADD_PANOTING_REQUEST = "ADD_PANOTING_REQUEST";
export const ADD_PANOTING_SUCCESS = "ADD_PANOTING_SUCCESS";
export const ADD_PANOTING_FAILURE = "ADD_PANOTING_FAILURE";

export const CREATE_SERVICE_LETTER_REQUEST = "CREATE_SERVICE_LETTER_REQUEST";
export const CREATE_SERVICE_LETTER_SUCCESS = "CREATE_SERVICE_LETTER_SUCCESS";
export const CREATE_SERVICE_LETTER_FAILURE = "CREATE_SERVICE_LETTER_FAILURE";

export const FETCH_PANOTING_REQUEST = "FETCH_PANOTING_REQUEST";
export const FETCH_PANOTING_SUCCESS = "FETCH_PANOTING_SUCCESS";
export const FETCH_PANOTING_FAILURE = "FETCH_PANOTING_FAILURE";

export const FETCH_PAENCLOSURE_REQUEST = "FETCH_PAENCLOSURE_REQUEST";
export const FETCH_PAENCLOSURE_SUCCESS = "FETCH_PAENCLOSURE_SUCCESS";
export const FETCH_PAENCLOSURE_FAILURE = "FETCH_PAENCLOSURE_FAILURE";

export const FETCH_SECTION_REQUEST = "FETCH_SECTION_REQUEST";
export const FETCH_SECTION_SUCCESS = "FETCH_SECTION_SUCCESS";
export const FETCH_SECTION_FAILURE = "FETCH_SECTION_FAILURE";

export const FETCH_SERVICENUMBER_REQUEST = "FETCH_SERVICENUMBER_REQUEST";
export const FETCH_SERVICENUMBER_SUCCESS = "FETCH_SERVICENUMBER_SUCCESS";
export const FETCH_SERVICENUMBER_FAILURE = "FETCH_SERVICENUMBER_FAILURE";

export const SENDFILESECTION_REQUEST = "SENDFILESECTION_REQUEST";
export const SENDFILESECTION_SUCCESS = "SENDFILESECTION_SUCCESS";
export const SENDFILESECTION_FAILURE = "SENDFILESECTION_FAILURE";

export const SENDFILESERVICENUMBER_REQUEST = "SENDFILESERVICENUMBER_REQUEST";
export const SENDFILESERVICENUMBER_SUCCESS = "SENDFILESERVICENUMBER_SUCCESS";
export const SENDFILESERVICENUMBER_FAILURE = "SENDFILESERVICENUMBER_FAILURE";

export const PADRAFT_REQUEST = "PADRAFT_REQUEST";
export const PADRAFT_SUCCESS = "PADRAFT_SUCCESS";
export const PADRAFT_FAILURE = "PADRAFT_FAILURE";

export const PART_CASE_DATA_REQUEST = "PART_CASE_DATA_REQUEST";
export const PART_CASE_DATA_SUCCESS = "PART_CASE_DATA_SUCCESS";
export const PART_CASE_DATA_FAILURE = "PART_CASE_DATA_FAILURE";

export const SPLITVIEW_INBOXDATA_REQUEST = "SPLITVIEW_INBOXDATA_REQUEST";
export const SPLITVIEW_INBOXDATA_SUCCESS = "SPLITVIEW_INBOXDATA_SUCCESS";
export const SPLITVIEW_INBOXDATA_FAILURE = "SPLITVIEW_INBOXDATA_FAILURE";

export const PA_FILE_DATA_REQUEST = "PA_FILE_DATA_REQUEST";
export const PA_FILE_DATA_SUCCESS = "PA_FILE_DATA_SUCCESS";
export const PA_FILE_DATA_FAILURE = "PA_FILE_DATA_FAILURE";

export const PARTCASE_TAG_REQUEST = "PARTCASE_TAG_REQUEST";
export const PARTCASE_TAG_SUCCESS = "PARTCASE_TAG_SUCCESS";
export const PARTCASE_TAG_FAILURE = "PARTCASE_TAG_FAILURE";

export const FETCH_PARTCASE_TAG_REQUEST = "FETCH_PARTCASE_TAG_REQUEST";
export const FETCH_PARTCASE_TAG_SUCCESS = "FETCH_PARTCASE_TAG_SUCCESS";
export const FETCH_PARTCASE_TAG_FAILURE = "FETCH_PARTCASE_TAG_FAILURE";

export const CREATE_PARTCASE_NOTING_REQUEST = "CREATE_PARTCASE_NOTING_REQUEST";
export const CREATE_PARTCASE_NOTING_SUCCESS = "CREATE_PARTCASE_NOTING_SUCCESS";
export const CREATE_PARTCASE_NOTING_FAILURE = "CREATE_PARTCASE_NOTING_FAILURE";

export const CREATE_COVER_LETTER_REQUEST = "CREATE_COVER_LETTER_REQUEST";
export const CREATE_COVER_LETTER_SUCCESS = "CREATE_COVER_LETTER_SUCCESS";
export const CREATE_COVER_LETTER_FAILURE = "CREATE_COVER_LETTER_FAILURE";

export const UPDATE_PARTCASE_STATUS_REQUEST = "UPDATE_PARTCASE_STATUS_REQUEST";
export const UPDATE_PARTCASE_STATUS_SUCCESS = "UPDATE_PARTCASE_STATUS_SUCCESS";
export const UPDATE_PARTCASE_STATUS_FAILURE = "UPDATE_PARTCASE_STATUS_FAILURE";

export const FETCH_HISTORY_REQUEST = "FETCH_HISTORY_REQUEST";
export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
export const FETCH_HISTORY_FAILURE = "FETCH_HISTORY_FAILURE";

export const SENDFILEINTERNALSERVICENUMBER_REQUEST =
  "SENDFILEINTERNALSERVICENUMBER_REQUEST";
export const SENDFILEINTERNALSERVICENUMBER_SUCCESS =
  "SENDFILEINTERNALSERVICENUMBER_SUCCESS";
export const SENDFILEINTERNALSERVICENUMBER_FAILURE =
  "SENDFILEINTERNALSERVICENUMBER_FAILURE";

export const FETCH_INTERNALSERVICENUMBER_REQUEST =
  "FETCH_INTERNALSERVICENUMBER_REQUEST";
export const FETCH_INTERNALSERVICENUMBER_SUCCESS =
  "FETCH_INTERNALSERVICENUMBER_SUCCESS";
export const FETCH_INTERNALSERVICENUMBER_FAILURE =
  "FETCH_INTERNALSERVICENUMBER_FAILURE";

export const THEME_CHANGE = "THEME_CHANGE";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const UPDATE_FILE_SUBJECT = "UPDATE_FILE_SUBJECT";
export const SIDENAV_CHANGE = "SIDENAV_CHANGE";
export const OPEN_PA_DRAFT = "OPEN_PA_DRAFT";
export const CHANGE_PA_FILE = "CHANGE_PA_FILE";
export const MYINFO_CHANGE = "MYINFO_CHANGE";
export const INSTANCE_CHANGE = "INSTANCE_CHANGE";

export const FETCH_PAWITHANNEXURE_REQUEST = "FETCH_PAWITHANNEXURE_REQUEST";
export const FETCH_PAWITHANNEXURE_SUCCESS = "FETCH_PAWITHANNEXURE_SUCCESS";
export const FETCH_PAWITHANNEXURE_FAILURE = "FETCH_PAWITHANNEXURE_FAILURE";

export const ROLLBACK_PA_REQUEST = "ROLLBACK_PA_REQUEST";
export const ROLLBACK_PA_SUCCESS = "ROLLBACK_PA_SUCCESS";
export const ROLLBACK_PA_FAILURE = "ROLLBACK_PA_FAILURE";

export const GET_CABINATE_REQUEST = "GET_CABINATE_REQUEST";
export const GET_CABINATE_SUCCESS = "GET_CABINATE_SUCCESS";
export const GET_CABINATE_FAILURE = "GET_CABINATE_FAILURE";

export const ADD_TO_FAVOURITE_REQUEST = "ADD_TO_FAVOURITE_REQUEST";
export const ADD_TO_FAVOURITE_SUCCESS = "ADD_TO_FAVOURITE_SUCCESS";
export const ADD_TO_FAVOURITE_FAILURE = "ADD_TO_FAVOURITE_FAILURE";

export const FETCH_FAVOURITE_LIST_REQUEST = "FETCH_FAVOURITE_LIST_REQUEST";
export const FETCH_FAVOURITE_LIST_SUCCESS = "FETCH_FAVOURITE_LIST_SUCCESS";
export const FETCH_FAVOURITE_LIST_FAILURE = "FETCH_FAVOURITE_LIST_FAILURE";

export const DELETE_FAVOURITE_REQUEST = "DELETE_FAVOURITE_REQUEST";
export const DELETE_FAVOURITE_SUCCESS = "DELETE_FAVOURITE_SUCCESS";
export const DELETE_FAVOURITE_FAILURE = "DELETE_FAVOURITE_FAILURE";

export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILURE = "GET_NOTIFICATION_FAILURE";

export const STATUS_NOTIFICATION_REQUEST = "STATUS_NOTIFICATION_REQUEST";
export const STATUS_NOTIFICATION_SUCCESS = "STATUS_NOTIFICATION_SUCCESS";
export const STATUS_NOTIFICATION_FAILURE = "STATUS_NOTIFICATION_FAILURE";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATION_FAILURE";

export const DELETE_ALL_NOTIFICATION_REQUEST =
  "DELETE_ALL_NOTIFICATION_REQUEST";
export const DELETE_ALL_NOTIFICATION_SUCCESS =
  "DELETE_ALL_NOTIFICATION_SUCCESS";
export const DELETE_ALL_NOTIFICATION_FAILURE =
  "DELETE_ALL_NOTIFICATION_FAILURE";

export const RETURN_PA_REQUEST = "RETURN_PA_REQUEST";
export const RETURN_PA_SUCCESS = "RETURN_PA_SUCCESS";
export const RETURN_PA_FAILURE = "RETURN_PA_FAILURE";

export const SIDENAV_REQUEST = "SIDENAV_REQUEST";
export const SIDENAV_SUCCESS = "SIDENAV_SUCCESS";
export const SIDENAV_FAILURE = "SIDENAV_FAILURE";


export const GET_REQUEST_DATA = "GET_REQUEST_DATA";
export const SET_REQUEST_DATA = "SET_REQUEST_DATA";
export const FAIL_REQUEST_DATA = "FAIL_REQUEST_DATA";

export const STATUS_REQUEST = 'STATUS_REQUEST'
export const STATUS_SUCCESS = 'STATUS_SUCCESS'
export const STATUS_FAILURE = 'STATUS_FAILURE'

// ADMIN MODULE APIS::
export const ADMIN_DBOARD_COUNT_REQUEST="ADMIN_DBOARD_COUNT_REQUEST"
export const ADMIN_DBOARD_COUNT_SUCCESS="ADMIN_DBOARD_COUNT_SUCCESS"
export const ADMIN_DBOARD_COUNT_FAILURE="ADMIN_DBOARD_COUNT_FAILURE"

export const GET_ADMIN_USERS_REQUEST="GET_ADMIN_USERS_REQUEST"
export const GET_ADMIN_USERS_SUCCESS="GET_ADMIN_USERS_SUCCESS"
export const GET_ADMIN_USERS_FAILURE="GET_ADMIN_USERS_FAILURE"

export const GET_ADMIN_ROLES_REQUEST="GET_ADMIN_ROLES_REQUEST"
export const GET_ADMIN_ROLES_SUCCESS="GET_ADMIN_ROLES_SUCCESS"
export const GET_ADMIN_ROLES_FAILURE="GET_ADMIN_ROLES_FAILURE"

export const GET_ADMIN_DEPARTMENTS_REQUEST="GET_ADMIN_DEPARTMENTS_REQUEST"
export const GET_ADMIN_DEPARTMENTS_SUCCESS="GET_ADMIN_DEPARTMENTS_SUCCESS"
export const GET_ADMIN_DEPARTMENTS_FAILURE="GET_ADMIN_DEPARTMENTS_FAILURE"
export const ADVANCE_SEARCH_REQUEST = "ADVANCE_SEARCH_REQUEST";
export const ADVANCE_SEARCH_SUCCESS = "ADVANCE_SEARCH_SUCCESS";
export const ADVANCE_SEARCH_FAILURE = "ADVANCE_SEARCH_FAILURE";

/* ---------------------------------------------------------Rti constant----------------------------------------------------------- */
export const FETCH_RTI_REQUEST = "FETCH_RTI_REQUEST";
export const FETCH_RTI_SUCCESS = "FETCH_RTI_SUCCESS";
export const FETCH_RTI_FAILURE = "FETCH_RTI_FAILURE";

export const ADD_RTI_REQUEST = "ADD_RTI_REQUEST";
export const ADD_RTI_SUCCESS = "ADD_RTI_SUCCESS";
export const ADD_RTI_FAILURE = "ADD_RTI_FAILURE";

export const SAVE_RTI_DOC_REQUEST = "SAVE_RTI_DOC_REQUEST";
export const SAVE_RTI_DOC_SUCCESS = "SAVE_RTI_DOC_SUCCESS";
export const SAVE_RTI_DOC_FAILURE = "SAVE_RTI_DOC_FAILURE";

export const UPLOAD_RTI_ENCLOUSER_REQUEST = "UPLOAD_RTI_ENCLOUSER_REQUEST";
export const UPLOAD_RTI_ENCLOUSER_SUCCESS = "UPLOAD_RTI_ENCLOUSER_SUCCESS";
export const UPLOAD_RTI_ENCLOUSER_FAILURE = "UPLOAD_RTI_ENCLOUSER_FAILURE";

export const SPLITVIEW_RTIDATA_REQUEST = "SPLITVIEW_RTIDATA_REQUEST";
export const SPLITVIEW_RTIDATA_SUCCESS = "SPLITVIEW_RTIDATA_SUCCESS";
export const SPLITVIEW_RTIDATA_FAILURE = "SPLITVIEW_RTIDATA_FAILURE";

export const RTI_INBOX_REQUEST = "RTI_INBOX_REQUEST";
export const RTI_INBOX_SUCCESS = "RTI_INBOX_SUCCESS";
export const RTI_INBOX_FAILURE = "RTI_INBOX_FAILURE";


export const RTI_DEPARTMENT_REQUEST = "RTI_DEPARTMENT_REQUEST";
export const RTI_DEPARTMENT_SUCCESS = "RTI_DEPARTMENT_SUCCESS";
export const RTI_DEPARTMENT_FAILURE = "RTI_DEPARTMENT_FAILURE";

export const FORWARD_DEPT_REQUEST = "FORWARD_DEPT_REQUEST";
export const FORWARD_DEPT_SUCCESS = "FORWARD_DEPT_SUCCESS";
export const FORWARD_DEPT_FAILURE = "FORWARD_DEPT_FAILURE";

export const GET_ENCLOUSER_REQUEST = "GET_ENCLOUSER_REQUEST";
export const GET_ENCLOUSER_SUCCESS = "GET_ENCLOUSER_SUCCESS";
export const GET_ENCLOUSER_FAILURE = "GET_ENCLOUSER_FAILURE";

export const GET_NOTING_REQUEST = "GET_NOTING_REQUEST";
export const GET_NOTING_SUCCESS = "GET_NOTING_SUCCESS";
export const GET_NOTING_FAILURE = "GET_NOTING_FAILURE";
// meeting module

export const GET_DEPARTMENT_REQUEST = 'GET_DEPARTMENT_REQUEST'
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS'
export const GET_DEPARTMENT_FAILURE = 'GET_DEPARTMENT_FAILURE'

export const CREATE_MEETING_REQUEST = 'CREATE_MEETING_REQUEST'
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS'
export const CREATE_MEETING_FAILURE = 'CREATE_MEETING_FAILURE'

export const GET_USERNAME_REQUEST = 'GET_USERNAME_REQUEST '
export const GET_USERNAME_SUCCESS = 'GET_USERNAME_SUCCESS '
export const GET_USERNAME_FAILURE = 'GET_USERNAME_FAILURE '


export const GET_MEETING_REQUEST = 'GET_MEETING_REQUEST'
export const GET_MEETING_SUCCESS = 'GET_MEETING_SUCCESS'
export const GET_MEETING_FAILURE = 'GET_MEETING_FAILURE'

export const GET_MEETINGDEPT_REQUEST = 'GET_MEETINGDEPT_REQUEST'
export const GET_MEETINGDEPT_SUCCESS = 'GET_MEETINGDEPT_SUCCESS'
export const GET_MEETINGDEPT_FAILURE = 'GET_MEETINGDEPT_FAILURE'

export const GET_ATTENDEES_REQUEST = 'GET_ATTENDEES_REQUEST'
export const GET_ATTENDEES_SUCCESS = 'GET_ATTENDEES_SUCCESS'
export const GET_ATTENDEES_FAILURE = 'GET_ATTENDEES_FAILURE'

export const POST_ATTENDEES_REQUEST = 'POST_ATTENDEES_REQUEST'
export const POST_ATTENDEES_SUCCESS = 'POST_ATTENDEES_SUCCESS'
export const POST_ATTENDEES_FAILURE = 'POST_ATTENDEES_FAILURE'

export const SEND_CHAIRMAN_REQUEST = 'SEND_CHAIRMAN_REQUEST'
export const SEND_CHAIRMAN_SUCCESS = 'SEND_CHAIRMAN_SUCCESS'
export const SEND_CHAIRMAN_FAILURE = 'SEND_CHAIRMAN_FAILURE'


export const POST_AGENDA_REQUEST = 'POST_AGENDA_REQUEST'
export const POST_AGENDA_SUCCESS = 'POST_AGENDA_SUCCESS'
export const POST_AGENDA_FAILURE = 'POST_AGENDA_FAILURE'



export const GET_AGENDA_REQUEST = 'GET_AGENDA_REQUEST'
export const GET_AGENDA_SUCCESS = 'GET_AGENDA_SUCCESS'
export const GET_AGENDA_FAILURE = 'GET_AGENDA_FAILURE'

export const GET_INBOXDATA_REQUEST = 'GET_INBOXDATA_REQUEST'
export const GET_INBOXDATA_SUCCESS = 'GET_INBOXDATA_SUCCESS'
export const GET_INBOXDATA_FAILURE = 'GET_INBOXDATA_FAILURE'


export const GET_CHAIRMANINBOX_DETAILS_REQUEST = 'GET_CHAIRMANINBOX_DETAILS_REQUEST'
export const GET_CHAIRMANINBOX_DETAILS_SUCCESS = 'GET_CHAIRMANINBOX_DETAILS_SUCCESS'
export const GET_CHAIRMANINBOX_DETAILS_FAILURE = 'GET_CHAIRMANINBOX_DETAILS_FAILURE'


export const APPROVE_CHAIRMAN_REQUEST = 'APPROVE_CHAIRMAN_REQUEST'
export const APPROVE_CHAIRMAN_SUCCESS = 'APPROVE_CHAIRMAN_SUCCESS'
export const APPROVE_CHAIRMAN_FAILURE = 'APPROVE_CHAIRMAN_FAILURE'


export const REJECT_CHAIRMAN_REQUEST = 'REJECT_CHAIRMAN_REQUEST'
export const REJECT_CHAIRMAN_SUCCESS = 'REJECT_CHAIRMAN_SUCCESS'
export const REJECT_CHAIRMAN_FAILURE = 'REJECT_CHAIRMAN_FAILURE'


export const GET_CHAIRMANCOMMENT_REQUEST = 'GET_CHAIRMANCOMMENT_REQUEST'
export const GET_CHAIRMANCOMMENT_SUCCESS = 'GET_CHAIRMANCOMMENT_SUCCESS'
export const GET_CHAIRMANCOMMENT_FAILURE = 'GET_CHAIRMANCOMMENT_FAILURE'

export const GET_USERATTENDEE_REQUEST = 'GET_USERATTENDEE_REQUEST'
export const GET_USERATTENDEE_SUCCESS = 'GET_USERATTENDEE_SUCCESS'
export const GET_USERATTENDEE_FAILURE = 'GET_USERATTENDEE_FAILURE'


export const USER_FORWORD_MEETING_REQUEST = 'USER_FORWORD_MEETING_REQUEST'
export const USER_FORWORD_MEETING_SUCCESS = 'USER_FORWORD_MEETING_SUCCESS'
export const USER_FORWORD_MEETING_FAILURE = 'USER_FORWORD_MEETING_FAILURE'


export const USER_ACCEPT_MEETING_REQUEST = 'USER_ACCEPT_MEETING_REQUEST'
export const USER_ACCEPT_MEETING_SUCCESS = 'USER_ACCEPT_MEETING_SUCCESS'
export const USER_ACCEPT_MEETING_FAILURE = 'USER_ACCEPT_MEETING_FAILURE'

export const USER_REJECT_MEETING_REQUEST = 'USER_REJECT_MEETING_REQUEST'
export const USER_REJECT_MEETING_SUCCESS = 'USER_REJECT_MEETING_SUCCESS'
export const USER_REJECT_MEETING_FAILURE = 'USER_REJECT_MEETING_FAILURE'

export const RESHEDULE_MEETING_REQUEST = 'RESHEDULE_MEETING_REQUEST'
export const RESHEDULE_MEETING_SUCCESS = 'RESHEDULE_MEETING_SUCCESS'
export const RESHEDULE_MEETING_FAILURE = 'RESHEDULE_MEETING_FAILURE'

export const INITIATOR_CANCELMEETING_REQUEST = 'INITIATOR_CANCELMEETING_REQUEST'
export const INITIATOR_CANCELMEETING_SUCCESS = 'INITIATOR_CANCELMEETING_SUCCESS'
export const INITIATOR_CANCELMEETING_FAILURE = 'INITIATOR_CANCELMEETING_FAILURE'

export const INITIATOR_DECISION_MEETING_REQUEST = 'INITIATOR_DECISION_MEETING_REQUEST'
export const INITIATOR_DECISION_MEETING_SUCCESS = 'INITIATOR_DECISION_MEETING_SUCCESS'
export const INITIATOR_DECISION_MEETING_FAILURE = 'INITIATOR_DECISION_MEETING_FAILURE'

export const INITIATOR_GET_DECISION_MEETING_REQUEST = 'INITIATOR_GET_DECISION_MEETING_REQUEST'
export const INITIATOR_GET_DECISION_MEETING_SUCCESS = 'INITIATOR_GET_DECISION_MEETING_SUCCESS'
export const INITIATOR_GET_DECISION_MEETING_FAILURE = 'INITIATOR_GET_DECISION_MEETING_FAILURE'

export const INITIATOR_POST_TASK_REQUEST = 'INITIATOR_POST_TASK_REQUEST'
export const INITIATOR_POST_TASK_SUCCESS = 'INITIATOR_POST_TASK_SUCCESS'
export const INITIATOR_POST_TASK_FAILURE = 'INITIATOR_POST_TASK_FAILURE'

export const INITIATOR_GET_TASK_REQUEST = 'INITIATOR_GET_TASK_REQUEST'
export const INITIATOR_GET_TASK_SUCCESS = 'INITIATOR_GET_TASK_SUCCESS'
export const INITIATOR_GET_TASK_FAILURE = 'INITIATOR_GET_TASK_FAILURE'

export const POST_ATTACH_DOCUMENT_REQUEST = 'POST_ATTACH_DOCUMENT_REQUEST'
export const POST_ATTACH_DOCUMENT_SUCCESS = 'POST_ATTACH_DOCUMENT_SUCCESS'
export const POST_ATTACH_DOCUMENT_FAILURE = 'POST_ATTACH_DOCUMENT_FAILURE'

export const GET_ATTACH_DOCUMENT_REQUEST = 'GET_ATTACH_DOCUMENT_REQUEST'
export const GET_ATTACH_DOCUMENT_SUCCESS = 'GET_ATTACH_DOCUMENT_SUCCESS'
export const GET_ATTACH_DOCUMENT_FAILURE = 'GET_ATTACH_DOCUMENT_FAILURE'

export const POST_MEETINGMEMO_REQUEST = 'POST_MEETINGMEMO_REQUEST'
export const POST_MEETINGMEMO_SUCCESS = 'POST_MEETINGMEMO_SUCCESS'
export const POST_MEETINGMEMO_FAILURE = 'POST_MEETINGMEMO_FAILURE'

export const GET_MEETINGMEMO_REQUEST = 'GET_MEETINGMEMO_REQUEST'
export const GET_MEETINGMEMO_SUCCESS = 'GET_MEETINGMEMO_SUCCESS'
export const GET_MEETINGMEMO_FAILURE = 'GET_MEETINGMEMO_FAILURE'

export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST'
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS'
export const GET_GROUP_FAILURE = 'GET_GROUP_FAILURE'

export const POST_EXTERNALATTENDEES_REQUEST = 'POST_EXTERNALATTENDEES_REQUEST'
export const POST_EXTERNALATTENDEES_SUCCESS = 'POST_EXTERNALATTENDEES_SUCCESS'
export const POST_EXTERNALATTENDEES_FAILURE = 'POST_EXTERNALATTENDEES_FAILURE'

export const GET_EXTERNALATTENDEES_REQUEST = 'GET_EXTERNALATTENDEES_REQUEST'
export const GET_EXTERNALATTENDEES_SUCCESS = 'GET_EXTERNALATTENDEES_SUCCESS'
export const GET_EXTERNALATTENDEES_FAILURE = 'GET_EXTERNALATTENDEES_FAILURE'


export const  POST_AGENDA_DOCUMENT_REQUEST =  'POST_AGENDA_DOCUMENT_REQUEST'
export const  POST_AGENDA_DOCUMENT_SUCCESS =  'POST_AGENDA_DOCUMENT_SUCCESS'
export const  POST_AGENDA_DOCUMENT_FAILURE =  'POST_AGENDA_DOCUMENT_FAILURE'

export const  FREEZE_AGENDA_REQUEST =  'FREEZE_AGENDA_REQUEST'
export const  FREEZE_AGENDA_SUCCESS =  'FREEZE_AGENDA_SUCCESS'
export const  FREEZE_AGENDA_FAILURE =  'FREEZE_AGENDA_FAILURE'


export const SEND_FILTER_DATA_REQUEST = "SEND_FILTER_DATA_REQUEST"
export const SEND_FILTER_DATA_SUCCESS = "SEND_FILTER_DATA_SUCCESS"
export const SEND_FILTER_DATA_FAILURE = "SEND_FILTER_DATA_FAILURE"

export const UPDATE_SUBJECT_FILE_REQUEST = "UPDATE_SUBJECT_FILE_REQUEST";
export const UPDATE_SUBJECT_FILE_SUCCESS = "UPDATE_SUBJECT_FILE_SUCCESS";
export const UPDATE_SUBJECT_FILE_FAILURE = "UPDATE_SUBJECT_FILE_FAILURE";

// YELLOW NOTES AND REMARKS

export const SPLITVIEW_YELLOW_NOTES_REQUEST = "SPLITVIEW_YELLOW_NOTES_REQUEST";
export const SPLITVIEW_YELLOW_NOTES_SUCCESS = "SPLITVIEW_YELLOW_NOTES_SUCCESS";
export const SPLITVIEW_YELLOW_NOTES_FAILURE = "SPLITVIEW_YELLOW_NOTES_FAILURE";

export const SPLITVIEW_ADD_YELLOW_NOTE_REQUEST = "SPLITVIEW_ADD_YELLOW_NOTE_REQUEST";
export const SPLITVIEW_ADD_YELLOW_NOTE_SUCCESS = "SPLITVIEW_ADD_YELLOW_NOTE_SUCCESS";
export const SPLITVIEW_ADD_YELLOW_NOTE_FAILURE = "SPLITVIEW_ADD_YELLOW_NOTE_FAILURE";

export const SPLITVIEW_DELETE_YELLOW_NOTE_REQUEST = "SPLITVIEW_DELETE_YELLOW_NOTE_REQUEST";
export const SPLITVIEW_DELETE_YELLOW_NOTE_SUCCESS = "SPLITVIEW_DELETE_YELLOW_NOTE_SUCCESS";
export const SPLITVIEW_DELETE_YELLOW_NOTE_FAILURE = "SPLITVIEW_DELETE_YELLOW_NOTE_FAILURE";

export const SPLITVIEW_REMARKS_LIST_REQUEST = "SPLITVIEW_REMARKS_LIST_REQUEST";
export const SPLITVIEW_REMARKS_LIST_SUCCESS = "SPLITVIEW_REMARKS_LIST_SUCCESS";
export const SPLITVIEW_REMARKS_LIST_FAILURE = "SPLITVIEW_REMARKS_LIST_FAILURE";

export const SPLITVIEW_TEMPORARY_CLOSE_FILE_REQUEST = "SPLITVIEW_TEMPORARY_CLOSE_FILE_REQUEST";
export const SPLITVIEW_TEMPORARY_CLOSE_FILE_SUCCESS = "SPLITVIEW_TEMPORARY_CLOSE_FILE_SUCCESS";
export const SPLITVIEW_TEMPORARY_CLOSE_FILE_FAILURE = "SPLITVIEW_TEMPORARY_CLOSE_FILE_FAILURE";

export const GET_EXTERNAL_CABINET_REQUEST = "GET_CABINET_REQUEST";
export const GET_EXTERNAL_CABINET_SUCCESS = "GET_CABINET_SUCCESS";
export const GET_EXTERNAL_CABINET_FAILURE = "GET_CABINET_FAILURE";

export const GET_CABINET_PARTCASE_REQUEST = "GET_CABINET_REQUEST";
export const GET_CABINET_PARTCASE_SUCCESS = "GET_CABINET_SUCCESS";
export const GET_CABINET_PARTCASE_FAILURE = "GET_CABINET_FAILURE";

export const GET_OPEN_FILE_REQUEST = "GET_CABINET_REQUEST";
export const GET_OPEN_FILE_SUCCESS = "GET_CABINET_SUCCESS";
export const GET_OPEN_FILE_FAILURE = "GET_CABINET_FAILURE";